init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v1.0.2.$env:APPVEYOR_BUILD_NUMBER-alpha" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

image: Visual Studio 2015

configuration: Release

environment:
  LMVTestAgentUsername: SecretAgentTest Resident
  LMVTestAgentPassword:
    secure: bOoXrGfLiHjZlCG1tJ+nDQ==

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

build:
  project: LibreMetaverse.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: false

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

assembly_info:
  patch: true
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - del "C:\Program Files (x86)\MSBuild\4.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - nuget restore LibreMetaverse.sln

